---
abstract: 'fast function for converting markdown to HTML (requires C compiler)'
author:
  - 'Masayoshi Sekimura <sekimura@cpan.org>'
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Markdown-Discount
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/sekimura/text-markdown-discount.git
version: '0.13'
